### ISSUE TITLE
Update for Version 0.97a-RC11

### ISSUE THREAD

**Issue by Danielsoeller** [TobiaFi/TrulyAutomatedShips#3]
Hi, 
you just have to update in "mod_info.json" : "gameVersion": "0.97a-RC11",

**Comment by Danielsoeller** [comment]
As far as I can tell, it works fine

**Comment by Danielsoeller** [comment]
And by the way nice mod :)

**Comment by TobiaFi** [comment]
Hey, yes, I actually did that months ago but forgot to upload it. Taking care of it now
